server:
  port: 3033

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_customer
    username: postgres
    password: root
    driver-class: com.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: CUSTOMER
  config:
    import: optional:configserver:http://localhost:3036


#this is configured in github
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

