server:
  port: 3036

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fahim-Prodhan/bus-micro-config-service
          clone-on-start: true
