server:
  port: 3031
spring:
  datasource:
    url: jdbc:mysql://localhost:3360/micro_schedule
    username: root
    password: root
    driver-class: com.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: BUS-SCHEDULE
  config:
    import: optional:configserver:http://localhost:3036

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      routeBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

  retry:
    instances:
      routeBreaker:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      routeBreaker:
        limit-refresh-period: 4s
        limit-for-period: 3
        timeout-duration: 0s


